name: 'Telegram Action'
description: 'Send a customizable Telegram message through GitHub Actions.'
author: 'Bo-Yi Wu & Presentor'

## TODO: Refactor and add missing properties
inputs:
  token:
    description: 'telegram token'
    required: true
  to:
    description: 'telegram user'
    required: true
  message:
    description: 'telegram message'
    required: false
  message_file:
    description: 'overwrite the default message template with the contents of the specified file'
    required: false
  socks5:
    description: 'support socks5 proxy URL'
    required: false
  photo:
    description: 'send the photo message.'
    required: false
  document:
    description: 'send the document message.'
    required: false
  sticker:
    description: 'send the sticker message.'
    required: false
  audio:
    description: 'send the audio message.'
    required: false
  voice:
    description: 'send the voice message.'
    required: false
  location:
    description: 'send the location message.'
    required: false
  venue:
    description: 'send the venue message.'
    required: false
  video:
    description: 'send the video message.'
    required: false
  debug:
    description: 'enable debug mode.'
    required: false
  format:
    description: 'message format: markdown or html'
    required: false
  disable_web_page_preview:
    description: 'disables link previews for links in this message'
    required: false
  disable_notification:
    description: 'disables notifications for this message, supports sending a message without notification,'
    required: false

runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        #
        # NOTE: We need to pass all inputs as environment variables,
        #       when working with composite actions.
        #
        #       See following issue for more details:
        #       https://github.com/actions/runner/issues/665
        #
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_TO: ${{ inputs.to }}
        INPUT_MESSAGE: ${{ inputs.message }}
        INPUT_MESSAGE_FILE: ${{ inputs.message_file }}
        INPUT_SOCKS5: ${{ inputs.socks5 }}
        INPUT_PHOTO: ${{ inputs.photo }}
        INPUT_DOCUMENT: ${{ inputs.document }}
        INPUT_STICKER: ${{ inputs.sticker }}
        INPUT_AUDIO: ${{ inputs.audio }}
        INPUT_VOICE: ${{ inputs.voice }}
        INPUT_LOCATION: ${{ inputs.location }}
        INPUT_VENUE: ${{ inputs.venue }}
        INPUT_VIDEO: ${{ inputs.video }}
        INPUT_DEBUG: ${{ inputs.debug }}
        INPUT_FORMAT: ${{ inputs.format }}
        INPUT_DISABLE_WEB_PAGE_PREVIEW: ${{ inputs.disable_web_page_preview }}
        INPUT_DISABLE_NOTIFICATION: ${{ inputs.disable_notification }}

## TODO: Customize?
branding:
  icon: message-square
  color: blue
